title: FashionHub
description: >- 
  Your one-stop shop for the latest fashion trends.
baseurl: "/ecom-demo"
domain: https://pocketaces2.github.io
url: https://pocketaces2.github.io

# Build settings
theme: jekyll-theme-minimal

sass:
  sass_dir: _sass
